global:
  smtp_smarthost: 'prometheus.datascientest@gmail.com:587'            # SMTP server and port
  smtp_from: 'smtp.gmail.com:465'                                     # Sender email address
  smtp_auth_username: 'prometheus.datascientest@gmail.com'            # SMTP username
  smtp_auth_password: 'qsyhonvlraonufcg'                              # SMTP password
  smtp_require_tls: true

route:
  receiver: 'RoadAccidentsInFrance'
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'RoadAccidentsInFrance'
    email_configs:
      - to: 'aryan.absalan@gmail.com'      # Recipient email address
        send_resolved: true                 # Send alert when resolved
        text: "{{ .CommonAnnotations.description }}" # The body of the email
        html: "{{ .CommonAnnotations.description }}"  # You can use html here too
        headers:
          subject: 'Alert: {{ .CommonAnnotations.summary }}'   # Subject of the email
