services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  model_service:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - PREPROCESSOR_PATH=${PREPROCESSOR_PATH}
      - DATASET_PATH=${DATASET_PATH}
      - DATASET_NAME=${DATASET_NAME}
    ports:
      - "8001:8001"

volumes:
  mysql_data:
