global:
  scrape_interval: 15s  # Interval to scrape metrics

scrape_configs:
  - job_name: 'fastapi_app_accidents'
    static_configs:
      - targets: ['fastapi_app_accidents:8000']  

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
