data_ingestion:
  root_dir:  data/raw
  source_URL: https://drive.google.com/drive/folders/1nH-wPgy9Txhv6yd4jiiZT7ZKhRJTVHYZ?usp=drive_link # it should be accidents_data.zip with accidents_data.csv
  local_data_file: data/raw/accidents_data.zip
  unzip_dir: data/raw

data_validation:
  root_dir: data
  unzip_dir: data/raw/accidents_data.csv
  STATUS_FILE: data/status.txt
  validated_data_path: data/validated/accidents_data_validated.csv
data_transformation: 
  root_dir: data/processed
  data_path: data/validated/accidents_data_validated.csv
  transform_data_path: data/transformed/accidents_data_transformed.csv

model_trainer:
  root_dir: models
  X_train_path: data/processed/X_train.csv
  X_test_path: data/processed/X_test.csv
  y_train_path: data/processed/y_train.csv
  y_test_path: data/processed/y_test.csv
  model_name: DecisionTreeClassifier_model.pkl

model_evaluation:
  root_dir: metrics
  X_test_path: data/processed/X_test.csv
  y_test_path: data/processed/y_test.csv
  model_path: models/DecisionTreeClassifier_model.pkl
  metric_file_name: metrics/metrics.json 

