name: Run Data Generator and DVC Pipeline Daily

on:
  schedule:
    # This cron expression runs the action every day at 06:45 PM UTC
    - cron: '45 06 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # You can change this to another runner, like windows-latest or macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (including DVC)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies
          pip install dvc  # Install DVC for pipeline execution

      # Step 4: Run the data_generator.py script
      - name: Run data_generator.py
        run: |
          python src/data/data_generator.py

      # Step 5: Sleep for 3 minutes 
      - name: Wait for 3 minutes
        run: |
          echo "Waiting for 3 minutes before running DVC pipeline..."
          sleep 1800  # Sleep for 180 seconds (3 minutes)

      # Step 6: Run the make_dataset.py script
      - name: Run make_dataset.py
        run: |
          python src/data/make_dataset.py

      # Step 7: Sleep for 5 minutes 
      - name: Wait for 5 minutes
        run: |
          echo "Waiting for 5 minutes before running DVC pipeline..."
          sleep 300  # Sleep for 300 seconds (5 minutes)

      # Step 8: Run DVC pipeline
      - name: Run DVC pipeline (dvc repro)
        run: |
          dvc repro
