name: Run Data Generator and DVC Pipeline Daily

on:
  schedule:
    - cron: '30 17 * * *'  # Run at 17:30 PM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: windows-latest  # Run specifically on Windows

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (including DVC)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc  # Install DVC

      # Step 4: Run the data_generator.py script
      - name: Run data_generator.py
        run: |
          python src\data\data_generator.py

      # Step 5: Wait for 1 minutes 
      - name: Wait for 1 minutes
        run: |
          timeout /t 60  # Wait 60 seconds on Windows

      # Step 6: Run the make_dataset.py script
      - name: Run make_dataset.py
        run: |
          python src\data\make_dataset.py

      # Step 7: Wait for 1 minutes 
      - name: Wait for 1 minutes
        run: |
          timeout /t 60 # Wait 60 seconds on Windows

      # Step 8: Run DVC pipeline
      - name: Run DVC pipeline (dvc repro)
        run: |
          dvc repro
