name: Run Data Generator and DVC Pipeline Daily

on:
  schedule:
    - cron: '30 17 * * *'  # Run at 17:30 PM UTC daily
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: windows-latest  # Run specifically on Windows

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (including DVC)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc  # Install DVC

      # Step 4: Download data_final.csv from Google Drive
      - name: Download data_final.csv from Google Drive
        run: |
          $url = "https://drive.google.com/uc?export=download&id=1q9e5vfl3Z3N3HiMNkwpDLA1rcBxr_Wd4" 
          $output = "D:\a\RoadAccidentsInFrance\notebooks\src\data\final\data_final.csv"

          # Ensure the file path's directory exists
          $dir = [System.IO.Path]::GetDirectoryName($output)
          if (-Not (Test-Path -Path $dir)) {
            New-Item -Path $dir -ItemType Directory
            Write-Host "Directory created: $dir"
          } else {
            Write-Host "Directory already exists: $dir"
          }
    
          # Download the file
          Invoke-WebRequest -Uri $url -OutFile $output
        shell: pwsh

      # Step 5: Run the data_generator.py script
      - name: Run data_generator.py
        run: |
          python src\data\data_generator.py

      # Step 6: Wait for 1 minutes 
      - name: Wait for 1 minutes
        run: |
          timeout /t 60  # Wait 60 seconds on Windows

      # Step 7: Run the make_dataset.py script
      - name: Run make_dataset.py
        run: |
          python src\data\make_dataset.py

      # Step 8: Wait for 1 minutes 
      - name: Wait for 1 minutes
        run: |
          timeout /t 60 # Wait 60 seconds on Windows

      # Step 9: Run DVC pipeline
      - name: Run DVC pipeline (dvc repro)
        run: |
          dvc repro
